/* eslint-disable */
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AliasAliasIdDelete
 */
export interface AliasAliasIdDelete {
    /**
     * 
     * @type {boolean}
     * @memberof AliasAliasIdDelete
     */
    deleted?: boolean;
}

/**
 * Check if a given object implements the AliasAliasIdDelete interface.
 */
export function instanceOfAliasAliasIdDelete(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AliasAliasIdDeleteFromJSON(json: any): AliasAliasIdDelete {
    return AliasAliasIdDeleteFromJSONTyped(json, false);
}

export function AliasAliasIdDeleteFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasAliasIdDelete {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deleted': !exists(json, 'deleted') ? undefined : json['deleted'],
    };
}

export function AliasAliasIdDeleteToJSON(value?: AliasAliasIdDelete | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deleted': value.deleted,
    };
}

