// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AliasAliasIdTogglePost
 */
export interface AliasAliasIdTogglePost {
    /**
     * 
     * @type {boolean}
     * @memberof AliasAliasIdTogglePost
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the AliasAliasIdTogglePost interface.
 */
export function instanceOfAliasAliasIdTogglePost(value: object): value is AliasAliasIdTogglePost {
    return true;
}

export function AliasAliasIdTogglePostFromJSON(json: any): AliasAliasIdTogglePost {
    return AliasAliasIdTogglePostFromJSONTyped(json, false);
}

export function AliasAliasIdTogglePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasAliasIdTogglePost {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function AliasAliasIdTogglePostToJSON(json: any): AliasAliasIdTogglePost {
    return AliasAliasIdTogglePostToJSONTyped(json, false);
}

export function AliasAliasIdTogglePostToJSONTyped(value?: AliasAliasIdTogglePost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
    };
}

