// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AliasAliasIdActivities
 */
export interface AliasAliasIdActivities {
    /**
     * 
     * @type {string}
     * @memberof AliasAliasIdActivities
     */
    action: string;
    /**
     * 
     * @type {string}
     * @memberof AliasAliasIdActivities
     */
    from: string;
    /**
     * Unix timestamp
     * @type {number}
     * @memberof AliasAliasIdActivities
     */
    timestamp: number;
    /**
     * 
     * @type {string}
     * @memberof AliasAliasIdActivities
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof AliasAliasIdActivities
     */
    reverseAlias: string;
    /**
     * 
     * @type {string}
     * @memberof AliasAliasIdActivities
     */
    reverseAliasAddress: string;
}

/**
 * Check if a given object implements the AliasAliasIdActivities interface.
 */
export function instanceOfAliasAliasIdActivities(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "from" in value;
    isInstance = isInstance && "timestamp" in value;
    isInstance = isInstance && "to" in value;
    isInstance = isInstance && "reverseAlias" in value;
    isInstance = isInstance && "reverseAliasAddress" in value;

    return isInstance;
}

export function AliasAliasIdActivitiesFromJSON(json: any): AliasAliasIdActivities {
    return AliasAliasIdActivitiesFromJSONTyped(json, false);
}

export function AliasAliasIdActivitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasAliasIdActivities {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'from': json['from'],
        'timestamp': json['timestamp'],
        'to': json['to'],
        'reverseAlias': json['reverse_alias'],
        'reverseAliasAddress': json['reverse_alias_address'],
    };
}

export function AliasAliasIdActivitiesToJSON(value?: AliasAliasIdActivities | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'from': value.from,
        'timestamp': value.timestamp,
        'to': value.to,
        'reverse_alias': value.reverseAlias,
        'reverse_alias_address': value.reverseAliasAddress,
    };
}

