// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MailboxModelRef } from './MailboxModelRef';
import {
    MailboxModelRefFromJSON,
    MailboxModelRefFromJSONTyped,
    MailboxModelRefToJSON,
    MailboxModelRefToJSONTyped,
} from './MailboxModelRef';
import type { AliasLatestActivity } from './AliasLatestActivity';
import {
    AliasLatestActivityFromJSON,
    AliasLatestActivityFromJSONTyped,
    AliasLatestActivityToJSON,
    AliasLatestActivityToJSONTyped,
} from './AliasLatestActivity';

/**
 * 
 * @export
 * @interface Alias
 */
export interface Alias {
    /**
     * 
     * @type {Date}
     * @memberof Alias
     */
    creationDate: Date;
    /**
     * 
     * @type {number}
     * @memberof Alias
     */
    creationTimestamp: number;
    /**
     * Email address
     * @type {string}
     * @memberof Alias
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Alias
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof Alias
     */
    enabled: boolean;
    /**
     * 
     * @type {number}
     * @memberof Alias
     */
    id: number;
    /**
     * 
     * @type {MailboxModelRef}
     * @memberof Alias
     */
    mailbox: MailboxModelRef;
    /**
     * 
     * @type {Array<MailboxModelRef>}
     * @memberof Alias
     */
    mailboxes: Array<MailboxModelRef>;
    /**
     * 
     * @type {AliasLatestActivity}
     * @memberof Alias
     */
    latestActivity: AliasLatestActivity;
    /**
     * 
     * @type {number}
     * @memberof Alias
     */
    nbBlock: number;
    /**
     * 
     * @type {number}
     * @memberof Alias
     */
    nbForward: number;
    /**
     * 
     * @type {number}
     * @memberof Alias
     */
    nbReply: number;
    /**
     * 
     * @type {string}
     * @memberof Alias
     */
    note: string;
    /**
     * 
     * @type {boolean}
     * @memberof Alias
     */
    pinned: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Alias
     */
    disablePgp: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Alias
     */
    supportPgp: boolean;
}

/**
 * Check if a given object implements the Alias interface.
 */
export function instanceOfAlias(value: object): value is Alias {
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    if (!('creationTimestamp' in value) || value['creationTimestamp'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mailbox' in value) || value['mailbox'] === undefined) return false;
    if (!('mailboxes' in value) || value['mailboxes'] === undefined) return false;
    if (!('latestActivity' in value) || value['latestActivity'] === undefined) return false;
    if (!('nbBlock' in value) || value['nbBlock'] === undefined) return false;
    if (!('nbForward' in value) || value['nbForward'] === undefined) return false;
    if (!('nbReply' in value) || value['nbReply'] === undefined) return false;
    if (!('note' in value) || value['note'] === undefined) return false;
    if (!('pinned' in value) || value['pinned'] === undefined) return false;
    if (!('disablePgp' in value) || value['disablePgp'] === undefined) return false;
    if (!('supportPgp' in value) || value['supportPgp'] === undefined) return false;
    return true;
}

export function AliasFromJSON(json: any): Alias {
    return AliasFromJSONTyped(json, false);
}

export function AliasFromJSONTyped(json: any, ignoreDiscriminator: boolean): Alias {
    if (json == null) {
        return json;
    }
    return {
        
        'creationDate': (new Date(json['creation_date'])),
        'creationTimestamp': json['creation_timestamp'],
        'email': json['email'],
        'name': json['name'],
        'enabled': json['enabled'],
        'id': json['id'],
        'mailbox': MailboxModelRefFromJSON(json['mailbox']),
        'mailboxes': ((json['mailboxes'] as Array<any>).map(MailboxModelRefFromJSON)),
        'latestActivity': AliasLatestActivityFromJSON(json['latest_activity']),
        'nbBlock': json['nb_block'],
        'nbForward': json['nb_forward'],
        'nbReply': json['nb_reply'],
        'note': json['note'],
        'pinned': json['pinned'],
        'disablePgp': json['disable_pgp'],
        'supportPgp': json['support_pgp'],
    };
}

export function AliasToJSON(json: any): Alias {
    return AliasToJSONTyped(json, false);
}

export function AliasToJSONTyped(value?: Alias | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creation_date': value['creationDate'].toISOString(),
        'creation_timestamp': value['creationTimestamp'],
        'email': value['email'],
        'name': value['name'],
        'enabled': value['enabled'],
        'id': value['id'],
        'mailbox': MailboxModelRefToJSON(value['mailbox']),
        'mailboxes': ((value['mailboxes'] as Array<any>).map(MailboxModelRefToJSON)),
        'latest_activity': AliasLatestActivityToJSON(value['latestActivity']),
        'nb_block': value['nbBlock'],
        'nb_forward': value['nbForward'],
        'nb_reply': value['nbReply'],
        'note': value['note'],
        'pinned': value['pinned'],
        'disable_pgp': value['disablePgp'],
        'support_pgp': value['supportPgp'],
    };
}

