// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AliasAliasIdContacts } from './AliasAliasIdContacts';
import {
    AliasAliasIdContactsFromJSON,
    AliasAliasIdContactsFromJSONTyped,
    AliasAliasIdContactsToJSON,
    AliasAliasIdContactsToJSONTyped,
} from './AliasAliasIdContacts';

/**
 * 
 * @export
 * @interface AliasAliasIdContactsModelArray
 */
export interface AliasAliasIdContactsModelArray {
    /**
     * 
     * @type {Array<AliasAliasIdContacts>}
     * @memberof AliasAliasIdContactsModelArray
     */
    contacts?: Array<AliasAliasIdContacts>;
}

/**
 * Check if a given object implements the AliasAliasIdContactsModelArray interface.
 */
export function instanceOfAliasAliasIdContactsModelArray(value: object): value is AliasAliasIdContactsModelArray {
    return true;
}

export function AliasAliasIdContactsModelArrayFromJSON(json: any): AliasAliasIdContactsModelArray {
    return AliasAliasIdContactsModelArrayFromJSONTyped(json, false);
}

export function AliasAliasIdContactsModelArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasAliasIdContactsModelArray {
    if (json == null) {
        return json;
    }
    return {
        
        'contacts': json['contacts'] == null ? undefined : ((json['contacts'] as Array<any>).map(AliasAliasIdContactsFromJSON)),
    };
}

export function AliasAliasIdContactsModelArrayToJSON(json: any): AliasAliasIdContactsModelArray {
    return AliasAliasIdContactsModelArrayToJSONTyped(json, false);
}

export function AliasAliasIdContactsModelArrayToJSONTyped(value?: AliasAliasIdContactsModelArray | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contacts': value['contacts'] == null ? undefined : ((value['contacts'] as Array<any>).map(AliasAliasIdContactsToJSON)),
    };
}

