// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AliasLatestActivityContact } from './AliasLatestActivityContact';
import {
    AliasLatestActivityContactFromJSON,
    AliasLatestActivityContactFromJSONTyped,
    AliasLatestActivityContactToJSON,
    AliasLatestActivityContactToJSONTyped,
} from './AliasLatestActivityContact';

/**
 * 
 * @export
 * @interface AliasLatestActivity
 */
export interface AliasLatestActivity {
    /**
     * 
     * @type {string}
     * @memberof AliasLatestActivity
     */
    action: string;
    /**
     * 
     * @type {AliasLatestActivityContact}
     * @memberof AliasLatestActivity
     */
    contact: AliasLatestActivityContact;
    /**
     * 
     * @type {number}
     * @memberof AliasLatestActivity
     */
    timestamp: number;
}

/**
 * Check if a given object implements the AliasLatestActivity interface.
 */
export function instanceOfAliasLatestActivity(value: object): value is AliasLatestActivity {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('contact' in value) || value['contact'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function AliasLatestActivityFromJSON(json: any): AliasLatestActivity {
    return AliasLatestActivityFromJSONTyped(json, false);
}

export function AliasLatestActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasLatestActivity {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'contact': AliasLatestActivityContactFromJSON(json['contact']),
        'timestamp': json['timestamp'],
    };
}

export function AliasLatestActivityToJSON(json: any): AliasLatestActivity {
    return AliasLatestActivityToJSONTyped(json, false);
}

export function AliasLatestActivityToJSONTyped(value?: AliasLatestActivity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'contact': AliasLatestActivityContactToJSON(value['contact']),
        'timestamp': value['timestamp'],
    };
}

