// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AliasSearchPost
 */
export interface AliasSearchPost {
    /**
     * Full-text search for the e-mail address of the alias
     * @type {string}
     * @memberof AliasSearchPost
     */
    query?: string;
}

/**
 * Check if a given object implements the AliasSearchPost interface.
 */
export function instanceOfAliasSearchPost(value: object): value is AliasSearchPost {
    return true;
}

export function AliasSearchPostFromJSON(json: any): AliasSearchPost {
    return AliasSearchPostFromJSONTyped(json, false);
}

export function AliasSearchPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasSearchPost {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : json['query'],
    };
}

export function AliasSearchPostToJSON(json: any): AliasSearchPost {
    return AliasSearchPostToJSONTyped(json, false);
}

export function AliasSearchPostToJSONTyped(value?: AliasSearchPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
    };
}

