// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AliasLatestActivityContact
 */
export interface AliasLatestActivityContact {
    /**
     * Email address
     * @type {string}
     * @memberof AliasLatestActivityContact
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AliasLatestActivityContact
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AliasLatestActivityContact
     */
    reverseAlias: string;
}

/**
 * Check if a given object implements the AliasLatestActivityContact interface.
 */
export function instanceOfAliasLatestActivityContact(value: object): value is AliasLatestActivityContact {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('reverseAlias' in value) || value['reverseAlias'] === undefined) return false;
    return true;
}

export function AliasLatestActivityContactFromJSON(json: any): AliasLatestActivityContact {
    return AliasLatestActivityContactFromJSONTyped(json, false);
}

export function AliasLatestActivityContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasLatestActivityContact {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
        'reverseAlias': json['reverse_alias'],
    };
}

export function AliasLatestActivityContactToJSON(json: any): AliasLatestActivityContact {
    return AliasLatestActivityContactToJSONTyped(json, false);
}

export function AliasLatestActivityContactToJSONTyped(value?: AliasLatestActivityContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'reverse_alias': value['reverseAlias'],
    };
}

