// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Simplified alias model returned by the export endpoint
 * @export
 * @interface AliasExport
 */
export interface AliasExport {
    /**
     * Email address
     * @type {string}
     * @memberof AliasExport
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof AliasExport
     */
    enabled: boolean;
}

/**
 * Check if a given object implements the AliasExport interface.
 */
export function instanceOfAliasExport(value: object): value is AliasExport {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function AliasExportFromJSON(json: any): AliasExport {
    return AliasExportFromJSONTyped(json, false);
}

export function AliasExportFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasExport {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'enabled': json['enabled'],
    };
}

export function AliasExportToJSON(json: any): AliasExport {
    return AliasExportToJSONTyped(json, false);
}

export function AliasExportToJSONTyped(value?: AliasExport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'enabled': value['enabled'],
    };
}

