// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AliasAliasIdActivities } from './AliasAliasIdActivities';
import {
    AliasAliasIdActivitiesFromJSON,
    AliasAliasIdActivitiesFromJSONTyped,
    AliasAliasIdActivitiesToJSON,
    AliasAliasIdActivitiesToJSONTyped,
} from './AliasAliasIdActivities';

/**
 * 
 * @export
 * @interface AliasAliasIdActivitiesModelArray
 */
export interface AliasAliasIdActivitiesModelArray {
    /**
     * 
     * @type {Array<AliasAliasIdActivities>}
     * @memberof AliasAliasIdActivitiesModelArray
     */
    activities?: Array<AliasAliasIdActivities>;
}

/**
 * Check if a given object implements the AliasAliasIdActivitiesModelArray interface.
 */
export function instanceOfAliasAliasIdActivitiesModelArray(value: object): value is AliasAliasIdActivitiesModelArray {
    return true;
}

export function AliasAliasIdActivitiesModelArrayFromJSON(json: any): AliasAliasIdActivitiesModelArray {
    return AliasAliasIdActivitiesModelArrayFromJSONTyped(json, false);
}

export function AliasAliasIdActivitiesModelArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasAliasIdActivitiesModelArray {
    if (json == null) {
        return json;
    }
    return {
        
        'activities': json['activities'] == null ? undefined : ((json['activities'] as Array<any>).map(AliasAliasIdActivitiesFromJSON)),
    };
}

export function AliasAliasIdActivitiesModelArrayToJSON(json: any): AliasAliasIdActivitiesModelArray {
    return AliasAliasIdActivitiesModelArrayToJSONTyped(json, false);
}

export function AliasAliasIdActivitiesModelArrayToJSONTyped(value?: AliasAliasIdActivitiesModelArray | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activities': value['activities'] == null ? undefined : ((value['activities'] as Array<any>).map(AliasAliasIdActivitiesToJSON)),
    };
}

