// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AliasAliasIdContacts
 */
export interface AliasAliasIdContacts {
    /**
     * Unique identifier for the email address.
     * @type {number}
     * @memberof AliasAliasIdContacts
     */
    id: number;
    /**
     * Email address for the contact.
     * @type {string}
     * @memberof AliasAliasIdContacts
     */
    contact: string;
    /**
     * 
     * @type {Date}
     * @memberof AliasAliasIdContacts
     */
    creationDate: Date;
    /**
     * Unix timestamp
     * @type {number}
     * @memberof AliasAliasIdContacts
     */
    creationTimestamp: number;
    /**
     * 
     * @type {Date}
     * @memberof AliasAliasIdContacts
     */
    lastEmailSentDate?: Date;
    /**
     * Unix timestamp when the last email was sent.
     * @type {number}
     * @memberof AliasAliasIdContacts
     */
    lastEmailSentTimestamp?: number;
    /**
     * Reverse alias for the email address.
     * @type {string}
     * @memberof AliasAliasIdContacts
     */
    reverseAlias: string;
    /**
     * Whether the email address is blocked for forwarding.
     * @type {boolean}
     * @memberof AliasAliasIdContacts
     */
    blockForward?: boolean;
    /**
     * Whether the contact already existed.
     * @type {boolean}
     * @memberof AliasAliasIdContacts
     */
    existed?: boolean;
}

/**
 * Check if a given object implements the AliasAliasIdContacts interface.
 */
export function instanceOfAliasAliasIdContacts(value: object): value is AliasAliasIdContacts {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('contact' in value) || value['contact'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    if (!('creationTimestamp' in value) || value['creationTimestamp'] === undefined) return false;
    if (!('reverseAlias' in value) || value['reverseAlias'] === undefined) return false;
    return true;
}

export function AliasAliasIdContactsFromJSON(json: any): AliasAliasIdContacts {
    return AliasAliasIdContactsFromJSONTyped(json, false);
}

export function AliasAliasIdContactsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasAliasIdContacts {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'contact': json['contact'],
        'creationDate': (new Date(json['creation_date'])),
        'creationTimestamp': json['creation_timestamp'],
        'lastEmailSentDate': json['last_email_sent_date'] == null ? undefined : (new Date(json['last_email_sent_date'])),
        'lastEmailSentTimestamp': json['last_email_sent_timestamp'] == null ? undefined : json['last_email_sent_timestamp'],
        'reverseAlias': json['reverse_alias'],
        'blockForward': json['block_forward'] == null ? undefined : json['block_forward'],
        'existed': json['existed'] == null ? undefined : json['existed'],
    };
}

export function AliasAliasIdContactsToJSON(json: any): AliasAliasIdContacts {
    return AliasAliasIdContactsToJSONTyped(json, false);
}

export function AliasAliasIdContactsToJSONTyped(value?: AliasAliasIdContacts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'contact': value['contact'],
        'creation_date': value['creationDate'].toISOString(),
        'creation_timestamp': value['creationTimestamp'],
        'last_email_sent_date': value['lastEmailSentDate'] == null ? value['lastEmailSentDate'] : value['lastEmailSentDate'].toISOString(),
        'last_email_sent_timestamp': value['lastEmailSentTimestamp'],
        'reverse_alias': value['reverseAlias'],
        'block_forward': value['blockForward'],
        'existed': value['existed'],
    };
}

