// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.7
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AliasAliasIdContactsPost
 */
export interface AliasAliasIdContactsPost {
    /**
     * Email address
     * @type {string}
     * @memberof AliasAliasIdContactsPost
     */
    contact: string;
}

/**
 * Check if a given object implements the AliasAliasIdContactsPost interface.
 */
export function instanceOfAliasAliasIdContactsPost(value: object): value is AliasAliasIdContactsPost {
    if (!('contact' in value) || value['contact'] === undefined) return false;
    return true;
}

export function AliasAliasIdContactsPostFromJSON(json: any): AliasAliasIdContactsPost {
    return AliasAliasIdContactsPostFromJSONTyped(json, false);
}

export function AliasAliasIdContactsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasAliasIdContactsPost {
    if (json == null) {
        return json;
    }
    return {
        
        'contact': json['contact'],
    };
}

export function AliasAliasIdContactsPostToJSON(json: any): AliasAliasIdContactsPost {
    return AliasAliasIdContactsPostToJSONTyped(json, false);
}

export function AliasAliasIdContactsPostToJSONTyped(value?: AliasAliasIdContactsPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contact': value['contact'],
    };
}

