// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.7
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AliasOptionsRecommendation
 */
export interface AliasOptionsRecommendation {
    /**
     * 
     * @type {string}
     * @memberof AliasOptionsRecommendation
     */
    alias: string;
    /**
     * 
     * @type {string}
     * @memberof AliasOptionsRecommendation
     */
    hostname: string;
}

/**
 * Check if a given object implements the AliasOptionsRecommendation interface.
 */
export function instanceOfAliasOptionsRecommendation(value: object): value is AliasOptionsRecommendation {
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    return true;
}

export function AliasOptionsRecommendationFromJSON(json: any): AliasOptionsRecommendation {
    return AliasOptionsRecommendationFromJSONTyped(json, false);
}

export function AliasOptionsRecommendationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasOptionsRecommendation {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'hostname': json['hostname'],
    };
}

export function AliasOptionsRecommendationToJSON(json: any): AliasOptionsRecommendation {
    return AliasOptionsRecommendationToJSONTyped(json, false);
}

export function AliasOptionsRecommendationToJSONTyped(value?: AliasOptionsRecommendation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias': value['alias'],
        'hostname': value['hostname'],
    };
}

