// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.7
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AliasAliasIdDelete
 */
export interface AliasAliasIdDelete {
    /**
     * 
     * @type {boolean}
     * @memberof AliasAliasIdDelete
     */
    deleted?: boolean;
}

/**
 * Check if a given object implements the AliasAliasIdDelete interface.
 */
export function instanceOfAliasAliasIdDelete(value: object): value is AliasAliasIdDelete {
    return true;
}

export function AliasAliasIdDeleteFromJSON(json: any): AliasAliasIdDelete {
    return AliasAliasIdDeleteFromJSONTyped(json, false);
}

export function AliasAliasIdDeleteFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasAliasIdDelete {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
    };
}

export function AliasAliasIdDeleteToJSON(json: any): AliasAliasIdDelete {
    return AliasAliasIdDeleteToJSONTyped(json, false);
}

export function AliasAliasIdDeleteToJSONTyped(value?: AliasAliasIdDelete | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
    };
}

