// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.7
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Alias } from './Alias';
import {
    AliasFromJSON,
    AliasFromJSONTyped,
    AliasToJSON,
    AliasToJSONTyped,
} from './Alias';

/**
 * 
 * @export
 * @interface AliasModelArray
 */
export interface AliasModelArray {
    /**
     * 
     * @type {Array<Alias>}
     * @memberof AliasModelArray
     */
    aliases?: Array<Alias>;
}

/**
 * Check if a given object implements the AliasModelArray interface.
 */
export function instanceOfAliasModelArray(value: object): value is AliasModelArray {
    return true;
}

export function AliasModelArrayFromJSON(json: any): AliasModelArray {
    return AliasModelArrayFromJSONTyped(json, false);
}

export function AliasModelArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasModelArray {
    if (json == null) {
        return json;
    }
    return {
        
        'aliases': json['aliases'] == null ? undefined : ((json['aliases'] as Array<any>).map(AliasFromJSON)),
    };
}

export function AliasModelArrayToJSON(json: any): AliasModelArray {
    return AliasModelArrayToJSONTyped(json, false);
}

export function AliasModelArrayToJSONTyped(value?: AliasModelArray | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aliases': value['aliases'] == null ? undefined : ((value['aliases'] as Array<any>).map(AliasToJSON)),
    };
}

