// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeyPost
 */
export interface ApiKeyPost {
    /**
     * The device's name, used to identify the API key for management purposes
     * @type {string}
     * @memberof ApiKeyPost
     */
    device: string;
}

/**
 * Check if a given object implements the ApiKeyPost interface.
 */
export function instanceOfApiKeyPost(value: object): value is ApiKeyPost {
    if (!('device' in value) || value['device'] === undefined) return false;
    return true;
}

export function ApiKeyPostFromJSON(json: any): ApiKeyPost {
    return ApiKeyPostFromJSONTyped(json, false);
}

export function ApiKeyPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyPost {
    if (json == null) {
        return json;
    }
    return {
        
        'device': json['device'],
    };
}

export function ApiKeyPostToJSON(json: any): ApiKeyPost {
    return ApiKeyPostToJSONTyped(json, false);
}

export function ApiKeyPostToJSONTyped(value?: ApiKeyPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device': value['device'],
    };
}

