// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthActivatePost
 */
export interface AuthActivatePost {
    /**
     * Email address
     * @type {string}
     * @memberof AuthActivatePost
     */
    email: string;
    /**
     * Activation code sent to email
     * @type {string}
     * @memberof AuthActivatePost
     */
    code: string;
}

/**
 * Check if a given object implements the AuthActivatePost interface.
 */
export function instanceOfAuthActivatePost(value: object): value is AuthActivatePost {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function AuthActivatePostFromJSON(json: any): AuthActivatePost {
    return AuthActivatePostFromJSONTyped(json, false);
}

export function AuthActivatePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthActivatePost {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'code': json['code'],
    };
}

export function AuthActivatePostToJSON(json: any): AuthActivatePost {
    return AuthActivatePostToJSONTyped(json, false);
}

export function AuthActivatePostToJSONTyped(value?: AuthActivatePost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'code': value['code'],
    };
}

