// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthMfaPost
 */
export interface AuthMfaPost {
    /**
     * OTP token that user enters
     * @type {string}
     * @memberof AuthMfaPost
     */
    mfaToken: string;
    /**
     * MFA key obtained in previous auth request
     * @type {string}
     * @memberof AuthMfaPost
     */
    mfaKey: string;
    /**
     * The device name, used to create an ApiKey associated with this device
     * @type {string}
     * @memberof AuthMfaPost
     */
    device: string;
}

/**
 * Check if a given object implements the AuthMfaPost interface.
 */
export function instanceOfAuthMfaPost(value: object): value is AuthMfaPost {
    if (!('mfaToken' in value) || value['mfaToken'] === undefined) return false;
    if (!('mfaKey' in value) || value['mfaKey'] === undefined) return false;
    if (!('device' in value) || value['device'] === undefined) return false;
    return true;
}

export function AuthMfaPostFromJSON(json: any): AuthMfaPost {
    return AuthMfaPostFromJSONTyped(json, false);
}

export function AuthMfaPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthMfaPost {
    if (json == null) {
        return json;
    }
    return {
        
        'mfaToken': json['mfa_token'],
        'mfaKey': json['mfa_key'],
        'device': json['device'],
    };
}

export function AuthMfaPostToJSON(json: any): AuthMfaPost {
    return AuthMfaPostToJSONTyped(json, false);
}

export function AuthMfaPostToJSONTyped(value?: AuthMfaPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mfa_token': value['mfaToken'],
        'mfa_key': value['mfaKey'],
        'device': value['device'],
    };
}

