/* eslint-disable */
// @ts-nocheck
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * OpenAPI spec version: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AuthMfaPost {
    /**
    * OTP token that user enters
    */
    'mfaToken': string;
    /**
    * MFA key obtained in previous auth request
    */
    'mfaKey': string;
    /**
    * The device name, used to create an ApiKey associated with this device
    */
    'device': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mfaToken",
            "baseName": "mfa_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "mfaKey",
            "baseName": "mfa_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "device",
            "baseName": "device",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AuthMfaPost.attributeTypeMap;
    }

    public constructor() {
    }
}

