// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthForgotPasswordPost
 */
export interface AuthForgotPasswordPost {
    /**
     * Email address
     * @type {string}
     * @memberof AuthForgotPasswordPost
     */
    email: string;
}

/**
 * Check if a given object implements the AuthForgotPasswordPost interface.
 */
export function instanceOfAuthForgotPasswordPost(value: object): value is AuthForgotPasswordPost {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AuthForgotPasswordPostFromJSON(json: any): AuthForgotPasswordPost {
    return AuthForgotPasswordPostFromJSONTyped(json, false);
}

export function AuthForgotPasswordPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthForgotPasswordPost {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function AuthForgotPasswordPostToJSON(json: any): AuthForgotPasswordPost {
    return AuthForgotPasswordPostToJSONTyped(json, false);
}

export function AuthForgotPasswordPostToJSONTyped(value?: AuthForgotPasswordPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

