// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthMfa
 */
export interface AuthMfa {
    /**
     * User's name, could be an empty string
     * @type {string}
     * @memberof AuthMfa
     */
    name: string;
    /**
     * If MFA is not enabled, the api key is returned right away.
     * @type {string}
     * @memberof AuthMfa
     */
    apiKey: string;
    /**
     * Email address
     * @type {string}
     * @memberof AuthMfa
     */
    email: string;
}

/**
 * Check if a given object implements the AuthMfa interface.
 */
export function instanceOfAuthMfa(value: object): value is AuthMfa {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AuthMfaFromJSON(json: any): AuthMfa {
    return AuthMfaFromJSONTyped(json, false);
}

export function AuthMfaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthMfa {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'apiKey': json['api_key'],
        'email': json['email'],
    };
}

export function AuthMfaToJSON(json: any): AuthMfa {
    return AuthMfaToJSONTyped(json, false);
}

export function AuthMfaToJSONTyped(value?: AuthMfa | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'api_key': value['apiKey'],
        'email': value['email'],
    };
}

