// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.7
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLogin
 */
export interface AuthLogin {
    /**
     * User's name, could be an empty string.
     * @type {string}
     * @memberof AuthLogin
     */
    name: string;
    /**
     * Email address
     * @type {string}
     * @memberof AuthLogin
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthLogin
     */
    mfaEnabled: boolean;
    /**
     * Only useful when user enables MFA. In this case, user needs to enter their OTP token in order to login.
     * @type {string}
     * @memberof AuthLogin
     */
    mfaKey: string;
    /**
     * If MFA is not enabled, the api key is returned right away.
     * @type {string}
     * @memberof AuthLogin
     */
    apiKey: string;
}

/**
 * Check if a given object implements the AuthLogin interface.
 */
export function instanceOfAuthLogin(value: object): value is AuthLogin {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('mfaEnabled' in value) || value['mfaEnabled'] === undefined) return false;
    if (!('mfaKey' in value) || value['mfaKey'] === undefined) return false;
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    return true;
}

export function AuthLoginFromJSON(json: any): AuthLogin {
    return AuthLoginFromJSONTyped(json, false);
}

export function AuthLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogin {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'mfaEnabled': json['mfa_enabled'],
        'mfaKey': json['mfa_key'],
        'apiKey': json['api_key'],
    };
}

export function AuthLoginToJSON(json: any): AuthLogin {
    return AuthLoginToJSONTyped(json, false);
}

export function AuthLoginToJSONTyped(value?: AuthLogin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'mfa_enabled': value['mfaEnabled'],
        'mfa_key': value['mfaKey'],
        'api_key': value['apiKey'],
    };
}

