// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginPost
 */
export interface AuthLoginPost {
    /**
     * Email address
     * @type {string}
     * @memberof AuthLoginPost
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost
     */
    device: string;
}

/**
 * Check if a given object implements the AuthLoginPost interface.
 */
export function instanceOfAuthLoginPost(value: object): value is AuthLoginPost {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('device' in value) || value['device'] === undefined) return false;
    return true;
}

export function AuthLoginPostFromJSON(json: any): AuthLoginPost {
    return AuthLoginPostFromJSONTyped(json, false);
}

export function AuthLoginPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginPost {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'device': json['device'],
    };
}

export function AuthLoginPostToJSON(json: any): AuthLoginPost {
    return AuthLoginPostToJSONTyped(json, false);
}

export function AuthLoginPostToJSONTyped(value?: AuthLoginPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'device': value['device'],
    };
}

