// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthReactivatePost
 */
export interface AuthReactivatePost {
    /**
     * Email address
     * @type {string}
     * @memberof AuthReactivatePost
     */
    email: string;
}

/**
 * Check if a given object implements the AuthReactivatePost interface.
 */
export function instanceOfAuthReactivatePost(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function AuthReactivatePostFromJSON(json: any): AuthReactivatePost {
    return AuthReactivatePostFromJSONTyped(json, false);
}

export function AuthReactivatePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthReactivatePost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function AuthReactivatePostToJSON(value?: AuthReactivatePost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

