// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.7
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactsContactIdDelete
 */
export interface ContactsContactIdDelete {
    /**
     * Whether the contact was successfully deleted.
     * @type {boolean}
     * @memberof ContactsContactIdDelete
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the ContactsContactIdDelete interface.
 */
export function instanceOfContactsContactIdDelete(value: object): value is ContactsContactIdDelete {
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function ContactsContactIdDeleteFromJSON(json: any): ContactsContactIdDelete {
    return ContactsContactIdDeleteFromJSONTyped(json, false);
}

export function ContactsContactIdDeleteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactsContactIdDelete {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'],
    };
}

export function ContactsContactIdDeleteToJSON(json: any): ContactsContactIdDelete {
    return ContactsContactIdDeleteToJSONTyped(json, false);
}

export function ContactsContactIdDeleteToJSONTyped(value?: ContactsContactIdDelete | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
    };
}

