// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomDomainCustomDomainIdTrashAliasesInner
 */
export interface CustomDomainCustomDomainIdTrashAliasesInner {
    /**
     * The deleted email address
     * @type {string}
     * @memberof CustomDomainCustomDomainIdTrashAliasesInner
     */
    alias: string;
    /**
     * Unix timestamp
     * @type {number}
     * @memberof CustomDomainCustomDomainIdTrashAliasesInner
     */
    deletionTimestamp: number;
}

/**
 * Check if a given object implements the CustomDomainCustomDomainIdTrashAliasesInner interface.
 */
export function instanceOfCustomDomainCustomDomainIdTrashAliasesInner(value: object): value is CustomDomainCustomDomainIdTrashAliasesInner {
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('deletionTimestamp' in value) || value['deletionTimestamp'] === undefined) return false;
    return true;
}

export function CustomDomainCustomDomainIdTrashAliasesInnerFromJSON(json: any): CustomDomainCustomDomainIdTrashAliasesInner {
    return CustomDomainCustomDomainIdTrashAliasesInnerFromJSONTyped(json, false);
}

export function CustomDomainCustomDomainIdTrashAliasesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomDomainCustomDomainIdTrashAliasesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'deletionTimestamp': json['deletion_timestamp'],
    };
}

export function CustomDomainCustomDomainIdTrashAliasesInnerToJSON(json: any): CustomDomainCustomDomainIdTrashAliasesInner {
    return CustomDomainCustomDomainIdTrashAliasesInnerToJSONTyped(json, false);
}

export function CustomDomainCustomDomainIdTrashAliasesInnerToJSONTyped(value?: CustomDomainCustomDomainIdTrashAliasesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias': value['alias'],
        'deletion_timestamp': value['deletionTimestamp'],
    };
}

