// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.7
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomDomainCustomDomainIdTrashAliasesInner } from './CustomDomainCustomDomainIdTrashAliasesInner';
import {
    CustomDomainCustomDomainIdTrashAliasesInnerFromJSON,
    CustomDomainCustomDomainIdTrashAliasesInnerFromJSONTyped,
    CustomDomainCustomDomainIdTrashAliasesInnerToJSON,
    CustomDomainCustomDomainIdTrashAliasesInnerToJSONTyped,
} from './CustomDomainCustomDomainIdTrashAliasesInner';

/**
 * 
 * @export
 * @interface CustomDomainCustomDomainIdTrash
 */
export interface CustomDomainCustomDomainIdTrash {
    /**
     * List of deleted aliases for this custom domain
     * @type {Array<CustomDomainCustomDomainIdTrashAliasesInner>}
     * @memberof CustomDomainCustomDomainIdTrash
     */
    aliases: Array<CustomDomainCustomDomainIdTrashAliasesInner>;
}

/**
 * Check if a given object implements the CustomDomainCustomDomainIdTrash interface.
 */
export function instanceOfCustomDomainCustomDomainIdTrash(value: object): value is CustomDomainCustomDomainIdTrash {
    if (!('aliases' in value) || value['aliases'] === undefined) return false;
    return true;
}

export function CustomDomainCustomDomainIdTrashFromJSON(json: any): CustomDomainCustomDomainIdTrash {
    return CustomDomainCustomDomainIdTrashFromJSONTyped(json, false);
}

export function CustomDomainCustomDomainIdTrashFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomDomainCustomDomainIdTrash {
    if (json == null) {
        return json;
    }
    return {
        
        'aliases': ((json['aliases'] as Array<any>).map(CustomDomainCustomDomainIdTrashAliasesInnerFromJSON)),
    };
}

export function CustomDomainCustomDomainIdTrashToJSON(json: any): CustomDomainCustomDomainIdTrash {
    return CustomDomainCustomDomainIdTrashToJSONTyped(json, false);
}

export function CustomDomainCustomDomainIdTrashToJSONTyped(value?: CustomDomainCustomDomainIdTrash | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aliases': ((value['aliases'] as Array<any>).map(CustomDomainCustomDomainIdTrashAliasesInnerToJSON)),
    };
}

