// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MailboxModelRef } from './MailboxModelRef';
import {
    MailboxModelRefFromJSON,
    MailboxModelRefFromJSONTyped,
    MailboxModelRefToJSON,
} from './MailboxModelRef';

/**
 * 
 * @export
 * @interface CustomDomain
 */
export interface CustomDomain {
    /**
     * 
     * @type {boolean}
     * @memberof CustomDomain
     */
    catchAll: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CustomDomain
     */
    creationDate: Date;
    /**
     * Unix timestamp
     * @type {number}
     * @memberof CustomDomain
     */
    creationTimestamp: number;
    /**
     * 
     * @type {string}
     * @memberof CustomDomain
     */
    domainName: string;
    /**
     * 
     * @type {number}
     * @memberof CustomDomain
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof CustomDomain
     */
    isVerified: boolean;
    /**
     * 
     * @type {Array<MailboxModelRef>}
     * @memberof CustomDomain
     */
    mailboxes: Array<MailboxModelRef>;
    /**
     * 
     * @type {string}
     * @memberof CustomDomain
     */
    name: string | null;
    /**
     * 
     * @type {number}
     * @memberof CustomDomain
     */
    nbAlias: number;
    /**
     * 
     * @type {boolean}
     * @memberof CustomDomain
     */
    randomPrefixGeneration: boolean;
}

/**
 * Check if a given object implements the CustomDomain interface.
 */
export function instanceOfCustomDomain(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "catchAll" in value;
    isInstance = isInstance && "creationDate" in value;
    isInstance = isInstance && "creationTimestamp" in value;
    isInstance = isInstance && "domainName" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "isVerified" in value;
    isInstance = isInstance && "mailboxes" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "nbAlias" in value;
    isInstance = isInstance && "randomPrefixGeneration" in value;

    return isInstance;
}

export function CustomDomainFromJSON(json: any): CustomDomain {
    return CustomDomainFromJSONTyped(json, false);
}

export function CustomDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomDomain {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'catchAll': json['catch_all'],
        'creationDate': (new Date(json['creation_date'])),
        'creationTimestamp': json['creation_timestamp'],
        'domainName': json['domain_name'],
        'id': json['id'],
        'isVerified': json['is_verified'],
        'mailboxes': ((json['mailboxes'] as Array<any>).map(MailboxModelRefFromJSON)),
        'name': json['name'],
        'nbAlias': json['nb_alias'],
        'randomPrefixGeneration': json['random_prefix_generation'],
    };
}

export function CustomDomainToJSON(value?: CustomDomain | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'catch_all': value.catchAll,
        'creation_date': (value.creationDate.toISOString()),
        'creation_timestamp': value.creationTimestamp,
        'domain_name': value.domainName,
        'id': value.id,
        'is_verified': value.isVerified,
        'mailboxes': ((value.mailboxes as Array<any>).map(MailboxModelRefToJSON)),
        'name': value.name,
        'nb_alias': value.nbAlias,
        'random_prefix_generation': value.randomPrefixGeneration,
    };
}

