// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.7
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomDomainCustomDomainIdPatch
 */
export interface CustomDomainCustomDomainIdPatch {
    /**
     * Enable or disable catch-all for this domain
     * @type {boolean}
     * @memberof CustomDomainCustomDomainIdPatch
     */
    catchAll?: boolean;
    /**
     * Enable or disable random prefix generation for this domain
     * @type {boolean}
     * @memberof CustomDomainCustomDomainIdPatch
     */
    randomPrefixGeneration?: boolean;
    /**
     * Display name for the custom domain
     * @type {string}
     * @memberof CustomDomainCustomDomainIdPatch
     */
    name?: string;
    /**
     * Array of mailbox IDs to associate with this domain
     * @type {Array<number>}
     * @memberof CustomDomainCustomDomainIdPatch
     */
    mailboxIds?: Array<number>;
}

/**
 * Check if a given object implements the CustomDomainCustomDomainIdPatch interface.
 */
export function instanceOfCustomDomainCustomDomainIdPatch(value: object): value is CustomDomainCustomDomainIdPatch {
    return true;
}

export function CustomDomainCustomDomainIdPatchFromJSON(json: any): CustomDomainCustomDomainIdPatch {
    return CustomDomainCustomDomainIdPatchFromJSONTyped(json, false);
}

export function CustomDomainCustomDomainIdPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomDomainCustomDomainIdPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'catchAll': json['catch_all'] == null ? undefined : json['catch_all'],
        'randomPrefixGeneration': json['random_prefix_generation'] == null ? undefined : json['random_prefix_generation'],
        'name': json['name'] == null ? undefined : json['name'],
        'mailboxIds': json['mailbox_ids'] == null ? undefined : json['mailbox_ids'],
    };
}

export function CustomDomainCustomDomainIdPatchToJSON(json: any): CustomDomainCustomDomainIdPatch {
    return CustomDomainCustomDomainIdPatchToJSONTyped(json, false);
}

export function CustomDomainCustomDomainIdPatchToJSONTyped(value?: CustomDomainCustomDomainIdPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'catch_all': value['catchAll'],
        'random_prefix_generation': value['randomPrefixGeneration'],
        'name': value['name'],
        'mailbox_ids': value['mailboxIds'],
    };
}

