// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.7
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomDomain } from './CustomDomain';
import {
    CustomDomainFromJSON,
    CustomDomainFromJSONTyped,
    CustomDomainToJSON,
    CustomDomainToJSONTyped,
} from './CustomDomain';
import type { ExportDataAppInfo } from './ExportDataAppInfo';
import {
    ExportDataAppInfoFromJSON,
    ExportDataAppInfoFromJSONTyped,
    ExportDataAppInfoToJSON,
    ExportDataAppInfoToJSONTyped,
} from './ExportDataAppInfo';
import type { AliasExport } from './AliasExport';
import {
    AliasExportFromJSON,
    AliasExportFromJSONTyped,
    AliasExportToJSON,
    AliasExportToJSONTyped,
} from './AliasExport';

/**
 * 
 * @export
 * @interface ExportData
 */
export interface ExportData {
    /**
     * List of all user aliases (simplified format for export)
     * @type {Array<AliasExport>}
     * @memberof ExportData
     */
    aliases: Array<AliasExport>;
    /**
     * List of all user custom domains
     * @type {Array<CustomDomain>}
     * @memberof ExportData
     */
    customDomains: Array<CustomDomain>;
    /**
     * 
     * @type {ExportDataAppInfo}
     * @memberof ExportData
     */
    appInfo: ExportDataAppInfo;
}

/**
 * Check if a given object implements the ExportData interface.
 */
export function instanceOfExportData(value: object): value is ExportData {
    if (!('aliases' in value) || value['aliases'] === undefined) return false;
    if (!('customDomains' in value) || value['customDomains'] === undefined) return false;
    if (!('appInfo' in value) || value['appInfo'] === undefined) return false;
    return true;
}

export function ExportDataFromJSON(json: any): ExportData {
    return ExportDataFromJSONTyped(json, false);
}

export function ExportDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportData {
    if (json == null) {
        return json;
    }
    return {
        
        'aliases': ((json['aliases'] as Array<any>).map(AliasExportFromJSON)),
        'customDomains': ((json['custom_domains'] as Array<any>).map(CustomDomainFromJSON)),
        'appInfo': ExportDataAppInfoFromJSON(json['app_info']),
    };
}

export function ExportDataToJSON(json: any): ExportData {
    return ExportDataToJSONTyped(json, false);
}

export function ExportDataToJSONTyped(value?: ExportData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aliases': ((value['aliases'] as Array<any>).map(AliasExportToJSON)),
        'custom_domains': ((value['customDomains'] as Array<any>).map(CustomDomainToJSON)),
        'app_info': ExportDataAppInfoToJSON(value['appInfo']),
    };
}

