// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Application-related user information
 * @export
 * @interface ExportDataAppInfo
 */
export interface ExportDataAppInfo {
    /**
     * User's full name
     * @type {string}
     * @memberof ExportDataAppInfo
     */
    name: string;
    /**
     * Email address
     * @type {string}
     * @memberof ExportDataAppInfo
     */
    email: string;
    /**
     * Whether the user is a premium user
     * @type {boolean}
     * @memberof ExportDataAppInfo
     */
    isPremium: boolean;
    /**
     * Whether the user is in trial period
     * @type {boolean}
     * @memberof ExportDataAppInfo
     */
    inTrial: boolean;
    /**
     * URL of the user's profile picture
     * @type {string}
     * @memberof ExportDataAppInfo
     */
    profilePicture?: string;
    /**
     * Maximum number of aliases for free plan users
     * @type {number}
     * @memberof ExportDataAppInfo
     */
    maxAliasFreePlan?: number;
}

/**
 * Check if a given object implements the ExportDataAppInfo interface.
 */
export function instanceOfExportDataAppInfo(value: object): value is ExportDataAppInfo {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('isPremium' in value) || value['isPremium'] === undefined) return false;
    if (!('inTrial' in value) || value['inTrial'] === undefined) return false;
    return true;
}

export function ExportDataAppInfoFromJSON(json: any): ExportDataAppInfo {
    return ExportDataAppInfoFromJSONTyped(json, false);
}

export function ExportDataAppInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportDataAppInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'isPremium': json['is_premium'],
        'inTrial': json['in_trial'],
        'profilePicture': json['profile_picture'] == null ? undefined : json['profile_picture'],
        'maxAliasFreePlan': json['max_alias_free_plan'] == null ? undefined : json['max_alias_free_plan'],
    };
}

export function ExportDataAppInfoToJSON(json: any): ExportDataAppInfo {
    return ExportDataAppInfoToJSONTyped(json, false);
}

export function ExportDataAppInfoToJSONTyped(value?: ExportDataAppInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'is_premium': value['isPremium'],
        'in_trial': value['inTrial'],
        'profile_picture': value['profilePicture'],
        'max_alias_free_plan': value['maxAliasFreePlan'],
    };
}

