// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.7
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Mailbox } from './Mailbox';
import {
    MailboxFromJSON,
    MailboxFromJSONTyped,
    MailboxToJSON,
    MailboxToJSONTyped,
} from './Mailbox';

/**
 * 
 * @export
 * @interface MailboxModelArray
 */
export interface MailboxModelArray {
    /**
     * 
     * @type {Array<Mailbox>}
     * @memberof MailboxModelArray
     */
    mailboxes?: Array<Mailbox>;
}

/**
 * Check if a given object implements the MailboxModelArray interface.
 */
export function instanceOfMailboxModelArray(value: object): value is MailboxModelArray {
    return true;
}

export function MailboxModelArrayFromJSON(json: any): MailboxModelArray {
    return MailboxModelArrayFromJSONTyped(json, false);
}

export function MailboxModelArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxModelArray {
    if (json == null) {
        return json;
    }
    return {
        
        'mailboxes': json['mailboxes'] == null ? undefined : ((json['mailboxes'] as Array<any>).map(MailboxFromJSON)),
    };
}

export function MailboxModelArrayToJSON(json: any): MailboxModelArray {
    return MailboxModelArrayToJSONTyped(json, false);
}

export function MailboxModelArrayToJSONTyped(value?: MailboxModelArray | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mailboxes': value['mailboxes'] == null ? undefined : ((value['mailboxes'] as Array<any>).map(MailboxToJSON)),
    };
}

