// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MailboxMailboxIdPut
 */
export interface MailboxMailboxIdPut {
    /**
     * If true, set the mailbox as the default mailbox.
     * @type {boolean}
     * @memberof MailboxMailboxIdPut
     */
    _default?: boolean;
    /**
     * Email address
     * @type {string}
     * @memberof MailboxMailboxIdPut
     */
    email?: string;
    /**
     * If true, cancel the email change of the mailbox.
     * @type {boolean}
     * @memberof MailboxMailboxIdPut
     */
    cancelEmailChange?: boolean;
}

/**
 * Check if a given object implements the MailboxMailboxIdPut interface.
 */
export function instanceOfMailboxMailboxIdPut(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MailboxMailboxIdPutFromJSON(json: any): MailboxMailboxIdPut {
    return MailboxMailboxIdPutFromJSONTyped(json, false);
}

export function MailboxMailboxIdPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxMailboxIdPut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_default': !exists(json, 'default') ? undefined : json['default'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'cancelEmailChange': !exists(json, 'cancel_email_change') ? undefined : json['cancel_email_change'],
    };
}

export function MailboxMailboxIdPutToJSON(value?: MailboxMailboxIdPut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'default': value._default,
        'email': value.email,
        'cancel_email_change': value.cancelEmailChange,
    };
}

