// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Mailbox
 */
export interface Mailbox {
    /**
     * Email address
     * @type {string}
     * @memberof Mailbox
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof Mailbox
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof Mailbox
     */
    _default: boolean;
    /**
     * Unix timestamp
     * @type {number}
     * @memberof Mailbox
     */
    creationTimestamp: number;
    /**
     * 
     * @type {number}
     * @memberof Mailbox
     */
    nbAlias: number;
    /**
     * 
     * @type {boolean}
     * @memberof Mailbox
     */
    verified: boolean;
}

/**
 * Check if a given object implements the Mailbox interface.
 */
export function instanceOfMailbox(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "_default" in value;
    isInstance = isInstance && "creationTimestamp" in value;
    isInstance = isInstance && "nbAlias" in value;
    isInstance = isInstance && "verified" in value;

    return isInstance;
}

export function MailboxFromJSON(json: any): Mailbox {
    return MailboxFromJSONTyped(json, false);
}

export function MailboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mailbox {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'id': json['id'],
        '_default': json['default'],
        'creationTimestamp': json['creation_timestamp'],
        'nbAlias': json['nb_alias'],
        'verified': json['verified'],
    };
}

export function MailboxToJSON(value?: Mailbox | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'id': value.id,
        'default': value._default,
        'creation_timestamp': value.creationTimestamp,
        'nb_alias': value.nbAlias,
        'verified': value.verified,
    };
}

