// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MailboxPost
 */
export interface MailboxPost {
    /**
     * Email address
     * @type {string}
     * @memberof MailboxPost
     */
    email?: string;
}

/**
 * Check if a given object implements the MailboxPost interface.
 */
export function instanceOfMailboxPost(value: object): value is MailboxPost {
    return true;
}

export function MailboxPostFromJSON(json: any): MailboxPost {
    return MailboxPostFromJSONTyped(json, false);
}

export function MailboxPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxPost {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function MailboxPostToJSON(json: any): MailboxPost {
    return MailboxPostToJSONTyped(json, false);
}

export function MailboxPostToJSONTyped(value?: MailboxPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

