/* eslint-disable */
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MailboxModelRef
 */
export interface MailboxModelRef {
    /**
     * Email address
     * @type {string}
     * @memberof MailboxModelRef
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof MailboxModelRef
     */
    id: number;
}

/**
 * Check if a given object implements the MailboxModelRef interface.
 */
export function instanceOfMailboxModelRef(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function MailboxModelRefFromJSON(json: any): MailboxModelRef {
    return MailboxModelRefFromJSONTyped(json, false);
}

export function MailboxModelRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxModelRef {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'id': json['id'],
    };
}

export function MailboxModelRefToJSON(value?: MailboxModelRef | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'id': value.id,
    };
}

