// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Setting
 */
export interface Setting {
    /**
     * Random alias generation style
     * @type {string}
     * @memberof Setting
     */
    aliasGenerator: SettingAliasGeneratorEnum;
    /**
     * Enable or disable notifications
     * @type {boolean}
     * @memberof Setting
     */
    notification: boolean;
    /**
     * Domain selection for random aliases
     * @type {string}
     * @memberof Setting
     */
    randomAliasDefaultDomain: string;
    /**
     * Display format for sender information
     * @type {string}
     * @memberof Setting
     */
    senderFormat: SettingSenderFormatEnum;
    /**
     * Suffix generation method for random aliases
     * @type {string}
     * @memberof Setting
     */
    randomAliasSuffix: SettingRandomAliasSuffixEnum;
}


/**
 * @export
 */
export const SettingAliasGeneratorEnum = {
    Word: 'word',
    Uuid: 'uuid'
} as const;
export type SettingAliasGeneratorEnum = typeof SettingAliasGeneratorEnum[keyof typeof SettingAliasGeneratorEnum];

/**
 * @export
 */
export const SettingSenderFormatEnum = {
    At: 'AT',
    A: 'A',
    NameOnly: 'NAME_ONLY',
    AtOnly: 'AT_ONLY',
    NoName: 'NO_NAME'
} as const;
export type SettingSenderFormatEnum = typeof SettingSenderFormatEnum[keyof typeof SettingSenderFormatEnum];

/**
 * @export
 */
export const SettingRandomAliasSuffixEnum = {
    Word: 'word',
    RandomString: 'random_string'
} as const;
export type SettingRandomAliasSuffixEnum = typeof SettingRandomAliasSuffixEnum[keyof typeof SettingRandomAliasSuffixEnum];


/**
 * Check if a given object implements the Setting interface.
 */
export function instanceOfSetting(value: object): value is Setting {
    if (!('aliasGenerator' in value) || value['aliasGenerator'] === undefined) return false;
    if (!('notification' in value) || value['notification'] === undefined) return false;
    if (!('randomAliasDefaultDomain' in value) || value['randomAliasDefaultDomain'] === undefined) return false;
    if (!('senderFormat' in value) || value['senderFormat'] === undefined) return false;
    if (!('randomAliasSuffix' in value) || value['randomAliasSuffix'] === undefined) return false;
    return true;
}

export function SettingFromJSON(json: any): Setting {
    return SettingFromJSONTyped(json, false);
}

export function SettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Setting {
    if (json == null) {
        return json;
    }
    return {
        
        'aliasGenerator': json['alias_generator'],
        'notification': json['notification'],
        'randomAliasDefaultDomain': json['random_alias_default_domain'],
        'senderFormat': json['sender_format'],
        'randomAliasSuffix': json['random_alias_suffix'],
    };
}

export function SettingToJSON(json: any): Setting {
    return SettingToJSONTyped(json, false);
}

export function SettingToJSONTyped(value?: Setting | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias_generator': value['aliasGenerator'],
        'notification': value['notification'],
        'random_alias_default_domain': value['randomAliasDefaultDomain'],
        'sender_format': value['senderFormat'],
        'random_alias_suffix': value['randomAliasSuffix'],
    };
}

