// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingPatch
 */
export interface SettingPatch {
    /**
     * Random alias generation style
     * @type {string}
     * @memberof SettingPatch
     */
    aliasGenerator?: SettingPatchAliasGeneratorEnum;
    /**
     * Enable or disable notifications
     * @type {boolean}
     * @memberof SettingPatch
     */
    notification?: boolean;
    /**
     * Domain selection for random aliases
     * @type {string}
     * @memberof SettingPatch
     */
    randomAliasDefaultDomain?: string;
    /**
     * Display format for sender information
     * @type {string}
     * @memberof SettingPatch
     */
    senderFormat?: SettingPatchSenderFormatEnum;
    /**
     * Suffix generation method for random aliases
     * @type {string}
     * @memberof SettingPatch
     */
    randomAliasSuffix?: SettingPatchRandomAliasSuffixEnum;
}


/**
 * @export
 */
export const SettingPatchAliasGeneratorEnum = {
    Word: 'word',
    Uuid: 'uuid'
} as const;
export type SettingPatchAliasGeneratorEnum = typeof SettingPatchAliasGeneratorEnum[keyof typeof SettingPatchAliasGeneratorEnum];

/**
 * @export
 */
export const SettingPatchSenderFormatEnum = {
    At: 'AT',
    A: 'A',
    NameOnly: 'NAME_ONLY',
    AtOnly: 'AT_ONLY',
    NoName: 'NO_NAME'
} as const;
export type SettingPatchSenderFormatEnum = typeof SettingPatchSenderFormatEnum[keyof typeof SettingPatchSenderFormatEnum];

/**
 * @export
 */
export const SettingPatchRandomAliasSuffixEnum = {
    Word: 'word',
    RandomString: 'random_string'
} as const;
export type SettingPatchRandomAliasSuffixEnum = typeof SettingPatchRandomAliasSuffixEnum[keyof typeof SettingPatchRandomAliasSuffixEnum];


/**
 * Check if a given object implements the SettingPatch interface.
 */
export function instanceOfSettingPatch(value: object): value is SettingPatch {
    return true;
}

export function SettingPatchFromJSON(json: any): SettingPatch {
    return SettingPatchFromJSONTyped(json, false);
}

export function SettingPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'aliasGenerator': json['alias_generator'] == null ? undefined : json['alias_generator'],
        'notification': json['notification'] == null ? undefined : json['notification'],
        'randomAliasDefaultDomain': json['random_alias_default_domain'] == null ? undefined : json['random_alias_default_domain'],
        'senderFormat': json['sender_format'] == null ? undefined : json['sender_format'],
        'randomAliasSuffix': json['random_alias_suffix'] == null ? undefined : json['random_alias_suffix'],
    };
}

export function SettingPatchToJSON(json: any): SettingPatch {
    return SettingPatchToJSONTyped(json, false);
}

export function SettingPatchToJSONTyped(value?: SettingPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias_generator': value['aliasGenerator'],
        'notification': value['notification'],
        'random_alias_default_domain': value['randomAliasDefaultDomain'],
        'sender_format': value['senderFormat'],
        'random_alias_suffix': value['randomAliasSuffix'],
    };
}

