// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingDomain
 */
export interface SettingDomain {
    /**
     * The domain name available for random alias creation
     * @type {string}
     * @memberof SettingDomain
     */
    domain: string;
    /**
     * Whether the domain belongs to the user (true) or the platform (false)
     * @type {boolean}
     * @memberof SettingDomain
     */
    isCustom: boolean;
}

/**
 * Check if a given object implements the SettingDomain interface.
 */
export function instanceOfSettingDomain(value: object): value is SettingDomain {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('isCustom' in value) || value['isCustom'] === undefined) return false;
    return true;
}

export function SettingDomainFromJSON(json: any): SettingDomain {
    return SettingDomainFromJSONTyped(json, false);
}

export function SettingDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingDomain {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
        'isCustom': json['is_custom'],
    };
}

export function SettingDomainToJSON(json: any): SettingDomain {
    return SettingDomainToJSONTyped(json, false);
}

export function SettingDomainToJSONTyped(value?: SettingDomain | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
        'is_custom': value['isCustom'],
    };
}

