/* eslint-disable */
// @ts-nocheck
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * OpenAPI spec version: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UserInfo {
    /**
    * User's full name
    */
    'name': string;
    /**
    * Email address
    */
    'email': string;
    /**
    * Whether the user is a premium user or not
    */
    'isPremium': boolean;
    /**
    * Whether the user is in trial period or not
    */
    'inTrial': boolean;
    /**
    * URL of the user's profile picture
    */
    'profilePicture': string;
    'maxAliasFreePlan': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "isPremium",
            "baseName": "is_premium",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "inTrial",
            "baseName": "in_trial",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "profilePicture",
            "baseName": "profile_picture",
            "type": "string",
            "format": "url"
        },
        {
            "name": "maxAliasFreePlan",
            "baseName": "max_alias_free_plan",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

