// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * User's full name
     * @type {string}
     * @memberof UserInfo
     */
    name: string;
    /**
     * Email address
     * @type {string}
     * @memberof UserInfo
     */
    email: string;
    /**
     * Whether the user is a premium user or not
     * @type {boolean}
     * @memberof UserInfo
     */
    isPremium: boolean;
    /**
     * Whether the user is in trial period or not
     * @type {boolean}
     * @memberof UserInfo
     */
    inTrial: boolean;
    /**
     * URL of the user's profile picture
     * @type {string}
     * @memberof UserInfo
     */
    profilePicture: string;
    /**
     * 
     * @type {number}
     * @memberof UserInfo
     */
    maxAliasFreePlan: number;
}

/**
 * Check if a given object implements the UserInfo interface.
 */
export function instanceOfUserInfo(value: object): value is UserInfo {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('isPremium' in value) || value['isPremium'] === undefined) return false;
    if (!('inTrial' in value) || value['inTrial'] === undefined) return false;
    if (!('profilePicture' in value) || value['profilePicture'] === undefined) return false;
    if (!('maxAliasFreePlan' in value) || value['maxAliasFreePlan'] === undefined) return false;
    return true;
}

export function UserInfoFromJSON(json: any): UserInfo {
    return UserInfoFromJSONTyped(json, false);
}

export function UserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'isPremium': json['is_premium'],
        'inTrial': json['in_trial'],
        'profilePicture': json['profile_picture'],
        'maxAliasFreePlan': json['max_alias_free_plan'],
    };
}

export function UserInfoToJSON(json: any): UserInfo {
    return UserInfoToJSONTyped(json, false);
}

export function UserInfoToJSONTyped(value?: UserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'is_premium': value['isPremium'],
        'in_trial': value['inTrial'],
        'profile_picture': value['profilePicture'],
        'max_alias_free_plan': value['maxAliasFreePlan'],
    };
}

