// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.7
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserStats
 */
export interface UserStats {
    /**
     * 
     * @type {number}
     * @memberof UserStats
     */
    nbAlias?: number;
    /**
     * 
     * @type {number}
     * @memberof UserStats
     */
    nbBlock?: number;
    /**
     * 
     * @type {number}
     * @memberof UserStats
     */
    nbForward?: number;
    /**
     * 
     * @type {number}
     * @memberof UserStats
     */
    nbReply?: number;
}

/**
 * Check if a given object implements the UserStats interface.
 */
export function instanceOfUserStats(value: object): value is UserStats {
    return true;
}

export function UserStatsFromJSON(json: any): UserStats {
    return UserStatsFromJSONTyped(json, false);
}

export function UserStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserStats {
    if (json == null) {
        return json;
    }
    return {
        
        'nbAlias': json['nb_alias'] == null ? undefined : json['nb_alias'],
        'nbBlock': json['nb_block'] == null ? undefined : json['nb_block'],
        'nbForward': json['nb_forward'] == null ? undefined : json['nb_forward'],
        'nbReply': json['nb_reply'] == null ? undefined : json['nb_reply'],
    };
}

export function UserStatsToJSON(json: any): UserStats {
    return UserStatsToJSONTyped(json, false);
}

export function UserStatsToJSONTyped(value?: UserStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nb_alias': value['nbAlias'],
        'nb_block': value['nbBlock'],
        'nb_forward': value['nbForward'],
        'nb_reply': value['nbReply'],
    };
}

