name: pnpm-install
description: Install Node, pnpm and dependencies
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '24'
        registry-url: 'https://registry.npmjs.org'
    - uses: pnpm/action-setup@v4
    - name: Install dependencies
      run: pnpm install
      shell: bash