name: npm-install
description: Install Node, npm and dependencies
runs:
  using: 'composite'
  steps:
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: npm
        registry-url: 'https://registry.npmjs.org'
    - name: Update npm
      run: npm install -g npm@latest
      shell: bash
    - name: Install dependencies
      run: npm install
      shell: bash
