// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.7
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Alias,
  AliasAliasIdActivitiesModelArray,
  AliasAliasIdContacts,
  AliasAliasIdContactsModelArray,
  AliasAliasIdContactsPost,
  AliasAliasIdDelete,
  AliasAliasIdPatch,
  AliasAliasIdTogglePost,
  AliasCustomNewPost,
  AliasModelArray,
  AliasOptions,
  AliasRandomNewPost,
  AliasSearchPost,
  ContactsContactIdDelete,
  ContactsContactIdToggle,
  Success,
} from '../models/index';
import {
    AliasFromJSON,
    AliasToJSON,
    AliasAliasIdActivitiesModelArrayFromJSON,
    AliasAliasIdActivitiesModelArrayToJSON,
    AliasAliasIdContactsFromJSON,
    AliasAliasIdContactsToJSON,
    AliasAliasIdContactsModelArrayFromJSON,
    AliasAliasIdContactsModelArrayToJSON,
    AliasAliasIdContactsPostFromJSON,
    AliasAliasIdContactsPostToJSON,
    AliasAliasIdDeleteFromJSON,
    AliasAliasIdDeleteToJSON,
    AliasAliasIdPatchFromJSON,
    AliasAliasIdPatchToJSON,
    AliasAliasIdTogglePostFromJSON,
    AliasAliasIdTogglePostToJSON,
    AliasCustomNewPostFromJSON,
    AliasCustomNewPostToJSON,
    AliasModelArrayFromJSON,
    AliasModelArrayToJSON,
    AliasOptionsFromJSON,
    AliasOptionsToJSON,
    AliasRandomNewPostFromJSON,
    AliasRandomNewPostToJSON,
    AliasSearchPostFromJSON,
    AliasSearchPostToJSON,
    ContactsContactIdDeleteFromJSON,
    ContactsContactIdDeleteToJSON,
    ContactsContactIdToggleFromJSON,
    ContactsContactIdToggleToJSON,
    SuccessFromJSON,
    SuccessToJSON,
} from '../models/index';

export interface CreateContactRequest {
    aliasId: number;
    aliasAliasIdContactsPost: AliasAliasIdContactsPost;
}

export interface CreateCustomAliasRequest {
    aliasCustomNewPost: AliasCustomNewPost;
    hostname?: string;
}

export interface CreateRandomAliasRequest {
    aliasRandomNewPost: AliasRandomNewPost;
    hostname?: string;
    mode?: CreateRandomAliasModeEnum;
}

export interface DeleteAliasRequest {
    aliasId: number;
}

export interface DeleteContactRequest {
    contactId: number;
}

export interface GetActivitiesRequest {
    aliasId: number;
    pageId: number;
}

export interface GetAliasRequest {
    aliasId: number;
}

export interface GetAliasOptionsRequest {
    hostname?: string;
}

export interface GetAliasesRequest {
    pageId: number;
    pinned?: boolean;
    disabled?: boolean;
    enabled?: boolean;
}

export interface GetContactsRequest {
    aliasId: number;
    pageId: number;
}

export interface SearchAliasesRequest {
    pageId: number;
    pinned?: boolean;
    disabled?: boolean;
    enabled?: boolean;
    aliasSearchPost?: AliasSearchPost;
}

export interface ToggleAliasRequest {
    aliasId: number;
}

export interface ToggleContactBlockingRequest {
    contactId: number;
}

export interface UpdateAliasRequest {
    aliasId: number;
    aliasAliasIdPatch: AliasAliasIdPatch;
}

/**
 * 
 */
export class AliasApi extends runtime.BaseAPI {

    /**
     * Create a new contact for an alias by id.
     * Create contact
     */
    async createContactRaw(requestParameters: CreateContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AliasAliasIdContacts>> {
        if (requestParameters['aliasId'] == null) {
            throw new runtime.RequiredError(
                'aliasId',
                'Required parameter "aliasId" was null or undefined when calling createContact().'
            );
        }

        if (requestParameters['aliasAliasIdContactsPost'] == null) {
            throw new runtime.RequiredError(
                'aliasAliasIdContactsPost',
                'Required parameter "aliasAliasIdContactsPost" was null or undefined when calling createContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/aliases/{alias_id}/contacts`;
        urlPath = urlPath.replace(`{${"alias_id"}}`, encodeURIComponent(String(requestParameters['aliasId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AliasAliasIdContactsPostToJSON(requestParameters['aliasAliasIdContactsPost']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AliasAliasIdContactsFromJSON(jsonValue));
    }

    /**
     * Create a new contact for an alias by id.
     * Create contact
     */
    async createContact(requestParameters: CreateContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AliasAliasIdContacts> {
        const response = await this.createContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new custom alias
     * Create custom alias
     */
    async createCustomAliasRaw(requestParameters: CreateCustomAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Alias>> {
        if (requestParameters['aliasCustomNewPost'] == null) {
            throw new runtime.RequiredError(
                'aliasCustomNewPost',
                'Required parameter "aliasCustomNewPost" was null or undefined when calling createCustomAlias().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['hostname'] != null) {
            queryParameters['hostname'] = requestParameters['hostname'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/v3/alias/custom/new`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AliasCustomNewPostToJSON(requestParameters['aliasCustomNewPost']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AliasFromJSON(jsonValue));
    }

    /**
     * Create a new custom alias
     * Create custom alias
     */
    async createCustomAlias(requestParameters: CreateCustomAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Alias> {
        const response = await this.createCustomAliasRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new random alias
     * Create random alias
     */
    async createRandomAliasRaw(requestParameters: CreateRandomAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Alias>> {
        if (requestParameters['aliasRandomNewPost'] == null) {
            throw new runtime.RequiredError(
                'aliasRandomNewPost',
                'Required parameter "aliasRandomNewPost" was null or undefined when calling createRandomAlias().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['hostname'] != null) {
            queryParameters['hostname'] = requestParameters['hostname'];
        }

        if (requestParameters['mode'] != null) {
            queryParameters['mode'] = requestParameters['mode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/alias/random/new`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AliasRandomNewPostToJSON(requestParameters['aliasRandomNewPost']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AliasFromJSON(jsonValue));
    }

    /**
     * Create a new random alias
     * Create random alias
     */
    async createRandomAlias(requestParameters: CreateRandomAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Alias> {
        const response = await this.createRandomAliasRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete specific alias by id.
     * Delete alias
     */
    async deleteAliasRaw(requestParameters: DeleteAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AliasAliasIdDelete>> {
        if (requestParameters['aliasId'] == null) {
            throw new runtime.RequiredError(
                'aliasId',
                'Required parameter "aliasId" was null or undefined when calling deleteAlias().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/aliases/{alias_id}`;
        urlPath = urlPath.replace(`{${"alias_id"}}`, encodeURIComponent(String(requestParameters['aliasId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AliasAliasIdDeleteFromJSON(jsonValue));
    }

    /**
     * Delete specific alias by id.
     * Delete alias
     */
    async deleteAlias(requestParameters: DeleteAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AliasAliasIdDelete> {
        const response = await this.deleteAliasRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a contact by id.
     * Delete contact
     */
    async deleteContactRaw(requestParameters: DeleteContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactsContactIdDelete>> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling deleteContact().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/contacts/{contact_id}`;
        urlPath = urlPath.replace(`{${"contact_id"}}`, encodeURIComponent(String(requestParameters['contactId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactsContactIdDeleteFromJSON(jsonValue));
    }

    /**
     * Delete a contact by id.
     * Delete contact
     */
    async deleteContact(requestParameters: DeleteContactRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactsContactIdDelete> {
        const response = await this.deleteContactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get activities for specific alias by id.
     * Get activities
     */
    async getActivitiesRaw(requestParameters: GetActivitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AliasAliasIdActivitiesModelArray>> {
        if (requestParameters['aliasId'] == null) {
            throw new runtime.RequiredError(
                'aliasId',
                'Required parameter "aliasId" was null or undefined when calling getActivities().'
            );
        }

        if (requestParameters['pageId'] == null) {
            throw new runtime.RequiredError(
                'pageId',
                'Required parameter "pageId" was null or undefined when calling getActivities().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageId'] != null) {
            queryParameters['page_id'] = requestParameters['pageId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/aliases/{alias_id}/activities`;
        urlPath = urlPath.replace(`{${"alias_id"}}`, encodeURIComponent(String(requestParameters['aliasId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AliasAliasIdActivitiesModelArrayFromJSON(jsonValue));
    }

    /**
     * Get activities for specific alias by id.
     * Get activities
     */
    async getActivities(requestParameters: GetActivitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AliasAliasIdActivitiesModelArray> {
        const response = await this.getActivitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get specific alias by id.
     * Get alias
     */
    async getAliasRaw(requestParameters: GetAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Alias>> {
        if (requestParameters['aliasId'] == null) {
            throw new runtime.RequiredError(
                'aliasId',
                'Required parameter "aliasId" was null or undefined when calling getAlias().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/aliases/{alias_id}`;
        urlPath = urlPath.replace(`{${"alias_id"}}`, encodeURIComponent(String(requestParameters['aliasId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AliasFromJSON(jsonValue));
    }

    /**
     * Get specific alias by id.
     * Get alias
     */
    async getAlias(requestParameters: GetAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Alias> {
        const response = await this.getAliasRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * User alias info and suggestion. Used by the first extension screen when user opens the extension.
     * Get alias options
     */
    async getAliasOptionsRaw(requestParameters: GetAliasOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AliasOptions>> {
        const queryParameters: any = {};

        if (requestParameters['hostname'] != null) {
            queryParameters['hostname'] = requestParameters['hostname'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/v5/alias/options`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AliasOptionsFromJSON(jsonValue));
    }

    /**
     * User alias info and suggestion. Used by the first extension screen when user opens the extension.
     * Get alias options
     */
    async getAliasOptions(requestParameters: GetAliasOptionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AliasOptions> {
        const response = await this.getAliasOptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user aliases. Please note `pinned`, `disabled`, `enabled` are exclusive, i.e. only one can be present. They can only be set to `true`.
     * Get aliases
     */
    async getAliasesRaw(requestParameters: GetAliasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AliasModelArray>> {
        if (requestParameters['pageId'] == null) {
            throw new runtime.RequiredError(
                'pageId',
                'Required parameter "pageId" was null or undefined when calling getAliases().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageId'] != null) {
            queryParameters['page_id'] = requestParameters['pageId'];
        }

        if (requestParameters['pinned'] != null) {
            queryParameters['pinned'] = requestParameters['pinned'];
        }

        if (requestParameters['disabled'] != null) {
            queryParameters['disabled'] = requestParameters['disabled'];
        }

        if (requestParameters['enabled'] != null) {
            queryParameters['enabled'] = requestParameters['enabled'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/v2/aliases`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AliasModelArrayFromJSON(jsonValue));
    }

    /**
     * Get user aliases. Please note `pinned`, `disabled`, `enabled` are exclusive, i.e. only one can be present. They can only be set to `true`.
     * Get aliases
     */
    async getAliases(requestParameters: GetAliasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AliasModelArray> {
        const response = await this.getAliasesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get contacts for specific alias by id.
     * Get contacts
     */
    async getContactsRaw(requestParameters: GetContactsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AliasAliasIdContactsModelArray>> {
        if (requestParameters['aliasId'] == null) {
            throw new runtime.RequiredError(
                'aliasId',
                'Required parameter "aliasId" was null or undefined when calling getContacts().'
            );
        }

        if (requestParameters['pageId'] == null) {
            throw new runtime.RequiredError(
                'pageId',
                'Required parameter "pageId" was null or undefined when calling getContacts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageId'] != null) {
            queryParameters['page_id'] = requestParameters['pageId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/aliases/{alias_id}/contacts`;
        urlPath = urlPath.replace(`{${"alias_id"}}`, encodeURIComponent(String(requestParameters['aliasId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AliasAliasIdContactsModelArrayFromJSON(jsonValue));
    }

    /**
     * Get contacts for specific alias by id.
     * Get contacts
     */
    async getContacts(requestParameters: GetContactsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AliasAliasIdContactsModelArray> {
        const response = await this.getContactsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search user aliases. Please note `pinned`, `disabled`, `enabled` are exclusive, i.e. only one can be present. They can only be set to `true`.
     * Search aliases
     */
    async searchAliasesRaw(requestParameters: SearchAliasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AliasModelArray>> {
        if (requestParameters['pageId'] == null) {
            throw new runtime.RequiredError(
                'pageId',
                'Required parameter "pageId" was null or undefined when calling searchAliases().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageId'] != null) {
            queryParameters['page_id'] = requestParameters['pageId'];
        }

        if (requestParameters['pinned'] != null) {
            queryParameters['pinned'] = requestParameters['pinned'];
        }

        if (requestParameters['disabled'] != null) {
            queryParameters['disabled'] = requestParameters['disabled'];
        }

        if (requestParameters['enabled'] != null) {
            queryParameters['enabled'] = requestParameters['enabled'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/v2/aliases`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AliasSearchPostToJSON(requestParameters['aliasSearchPost']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AliasModelArrayFromJSON(jsonValue));
    }

    /**
     * Search user aliases. Please note `pinned`, `disabled`, `enabled` are exclusive, i.e. only one can be present. They can only be set to `true`.
     * Search aliases
     */
    async searchAliases(requestParameters: SearchAliasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AliasModelArray> {
        const response = await this.searchAliasesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Enable or disable specific alias by id.
     * Toggle alias
     */
    async toggleAliasRaw(requestParameters: ToggleAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AliasAliasIdTogglePost>> {
        if (requestParameters['aliasId'] == null) {
            throw new runtime.RequiredError(
                'aliasId',
                'Required parameter "aliasId" was null or undefined when calling toggleAlias().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/aliases/{alias_id}/toggle`;
        urlPath = urlPath.replace(`{${"alias_id"}}`, encodeURIComponent(String(requestParameters['aliasId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AliasAliasIdTogglePostFromJSON(jsonValue));
    }

    /**
     * Enable or disable specific alias by id.
     * Toggle alias
     */
    async toggleAlias(requestParameters: ToggleAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AliasAliasIdTogglePost> {
        const response = await this.toggleAliasRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Block or unblock a contact by id. Toggles the block_forward status.
     * Toggle contact blocking
     */
    async toggleContactBlockingRaw(requestParameters: ToggleContactBlockingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContactsContactIdToggle>> {
        if (requestParameters['contactId'] == null) {
            throw new runtime.RequiredError(
                'contactId',
                'Required parameter "contactId" was null or undefined when calling toggleContactBlocking().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/contacts/{contact_id}/toggle`;
        urlPath = urlPath.replace(`{${"contact_id"}}`, encodeURIComponent(String(requestParameters['contactId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContactsContactIdToggleFromJSON(jsonValue));
    }

    /**
     * Block or unblock a contact by id. Toggles the block_forward status.
     * Toggle contact blocking
     */
    async toggleContactBlocking(requestParameters: ToggleContactBlockingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContactsContactIdToggle> {
        const response = await this.toggleContactBlockingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update specific alias by id.
     * Update alias
     */
    async updateAliasRaw(requestParameters: UpdateAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Success>> {
        if (requestParameters['aliasId'] == null) {
            throw new runtime.RequiredError(
                'aliasId',
                'Required parameter "aliasId" was null or undefined when calling updateAlias().'
            );
        }

        if (requestParameters['aliasAliasIdPatch'] == null) {
            throw new runtime.RequiredError(
                'aliasAliasIdPatch',
                'Required parameter "aliasAliasIdPatch" was null or undefined when calling updateAlias().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/aliases/{alias_id}`;
        urlPath = urlPath.replace(`{${"alias_id"}}`, encodeURIComponent(String(requestParameters['aliasId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AliasAliasIdPatchToJSON(requestParameters['aliasAliasIdPatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessFromJSON(jsonValue));
    }

    /**
     * Update specific alias by id.
     * Update alias
     */
    async updateAlias(requestParameters: UpdateAliasRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Success> {
        const response = await this.updateAliasRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreateRandomAliasModeEnum = {
    Uuid: 'uuid',
    Word: 'word'
} as const;
export type CreateRandomAliasModeEnum = typeof CreateRandomAliasModeEnum[keyof typeof CreateRandomAliasModeEnum];
