// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.22.0
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExportData,
} from '../models/index';
import {
    ExportDataFromJSON,
    ExportDataToJSON,
} from '../models/index';

/**
 * 
 */
export class ImportExportApi extends runtime.BaseAPI {

    /**
     * Export user aliases in an importable CSV format that can be used in the settings screen
     * Export aliases as CSV
     */
    async exportAliasesAsCsvRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/export/aliases`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Export user aliases in an importable CSV format that can be used in the settings screen
     * Export aliases as CSV
     */
    async exportAliasesAsCsv(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.exportAliasesAsCsvRaw(initOverrides);
        return await response.value();
    }

    /**
     * Export comprehensive user data including aliases, custom domains, and app information
     * Export user data
     */
    async exportUserDataRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExportData>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/export/data`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExportDataFromJSON(jsonValue));
    }

    /**
     * Export comprehensive user data including aliases, custom domains, and app information
     * Export user data
     */
    async exportUserData(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExportData> {
        const response = await this.exportUserDataRaw(initOverrides);
        return await response.value();
    }

}
