// biome-ignore lint/format: generated file
// @ts-nocheck
type RequestCredentials = any;
type Response = any;
type RequestInit = any;
type FormData = any;
type WindowOrWorkerGlobalScope = any;
/* tslint:disable */
/* eslint-disable */
/**
 * SimpleLogin (unofficial)
 * The unofficial SimpleLogin API docs as OpenAPI 3.0.0 spec. This is based on the official markdown based docs, but written in OpenAPI to allow for easier integration with other tools and generation of client SDKs. Please do not contact the SimpleLogin team for support or issues with this API documentation.
 *
 * The version of the OpenAPI document: 4.74.6
 * Contact: contact@ketrwu.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Setting,
  SettingDomain,
  SettingPatch,
} from '../models/index';
import {
    SettingFromJSON,
    SettingToJSON,
    SettingDomainFromJSON,
    SettingDomainToJSON,
    SettingPatchFromJSON,
    SettingPatchToJSON,
} from '../models/index';

export interface UpdateUserSettingsRequest {
    settingPatch: SettingPatch;
}

/**
 * 
 */
export class SettingsApi extends runtime.BaseAPI {

    /**
     * Retrieve available domains for random alias creation
     * Get available domains for random aliases
     */
    async getAvailableDomainsForRandomAliasesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SettingDomain>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/v2/setting/domains`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SettingDomainFromJSON));
    }

    /**
     * Retrieve available domains for random alias creation
     * Get available domains for random aliases
     */
    async getAvailableDomainsForRandomAliases(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SettingDomain>> {
        const response = await this.getAvailableDomainsForRandomAliasesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Retrieve user\'s configuration preferences
     * Get user settings
     */
    async getUserSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Setting>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/setting`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingFromJSON(jsonValue));
    }

    /**
     * Retrieve user\'s configuration preferences
     * Get user settings
     */
    async getUserSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Setting> {
        const response = await this.getUserSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Modify user\'s configuration preferences
     * Update user settings
     */
    async updateUserSettingsRaw(requestParameters: UpdateUserSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Setting>> {
        if (requestParameters['settingPatch'] == null) {
            throw new runtime.RequiredError(
                'settingPatch',
                'Required parameter "settingPatch" was null or undefined when calling updateUserSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authentication"] = await this.configuration.apiKey("Authentication"); // apiKeyAuth authentication
        }


        let urlPath = `/setting`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SettingPatchToJSON(requestParameters['settingPatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SettingFromJSON(jsonValue));
    }

    /**
     * Modify user\'s configuration preferences
     * Update user settings
     */
    async updateUserSettings(requestParameters: UpdateUserSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Setting> {
        const response = await this.updateUserSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
